export const theme = {
  colors: {
    background: "#F8F6F2",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFEFC",
    primary: "#256F4B",
    primaryLight: "#7EBD9A",
    primaryDark: "#1A4D35",
    text: "#2C3E2E",
    textSecondary: "#5A6B5E",
    textMuted: "#8B978E",
    border: "#E5E8E4",
    borderLight: "#EEF0ED",
    accent: "#C17F59",
    accentLight: "#E8C4B0",
    error: "#B23A48",
    errorBg: "#FDE8EA",
    userBubble: "#256F4B",
    assistantBubble: "#EEF2EE",
    assistantBubbleText: "#2C3E2E",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    card: 20,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 18,
    xl: 20,
    full: 9999,
  },
  typography: {
    title: { fontSize: 24, fontWeight: "700" as const },
    subtitle: { fontSize: 18, fontWeight: "600" as const },
    body: { fontSize: 15 },
    caption: { fontSize: 13 },
    label: { fontSize: 14, fontWeight: "600" as const },
  },
};
